GET https://eu.api.blizzard.com/profile/user/wow
Authorization: {{CLIENT_ID}}:{{CLIENT_SECRET}}
Content-Type: application/json; charset=utf-8
Battlenet-Namespace: profile-eu
###
https://eu.api.blizzard.com/profile/user/wow?namespace=profile-eu&locale=en_US&access_token=EUMO7NMcHAIjEX6JzUCC1LWE7FnB6z07fW
